services:
  db:
    image: postgres:16
    container_name: foodmart_db
    environment:
      POSTGRES_USER: foodmart
      POSTGRES_PASSWORD: foodmart
      POSTGRES_DB: foodmart
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      - db
    ports:
      - "3000:3000"
